### ISSUE TITLE
Error in sys.excepthook in mailutility

### ISSUE THREAD

**Issue by nboumlaik** [Advestis/mailutility#3]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/site-packages/mailutility/mailmonitor.py", line 824, in overload_raise
    mm.send(to_send)
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/site-packages/mailutility/mailmonitor.py", line 787, in send
    self.mailbox.append(
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 408, in append
    return self._simple_command(name, mailbox, flags, date_time)
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 991, in _command
    while self._get_response():
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 1050, in _get_response
    resp = self._get_line()
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 1160, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF

Original exception was:
Traceback (most recent call last):
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 1022, in _command_complete
    typ, data = self._get_tagged_response(tag, expect_bye=logout)
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 1140, in _get_tagged_response
    self._check_bye()
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 936, in _check_bye
    raise self.abort(bye[-1].decode(self._encoding, 'replace'))
imaplib.abort: Connection closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/****/PycharmProjects/multiengine_69h/scripts/watchers.py", line 24, in <module>
    mail.monitor(
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/site-packages/mailutility/mailmonitor.py", line 436, in monitor
    self.pool.starmap(self._monitor, theargs)
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/site-packages/mailutility/mailmonitor.py", line 778, in _monitor
    the_while(self, timeout)
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/site-packages/mailutility/mailmonitor.py", line 729, in the_while
    shelf.mailbox.select(mailbox)
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 747, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/home/****/anaconda3/envs/multi_engines/lib/python3.8/imaplib.py", line 1024, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.abort: command: SELECT => Connection closed.
Failed to close the mailbox:
command: SELECT => socket error: EOF

Process finished with exit code 1

**Comment by ghost** [comment]
fixed in 054a9ca544015e7a0643b90b73c9d6862b3cbc48
